server.port=8080
server.address=0.0.0.0

spring.datasource.url=jdbc:oracle:thin:@//37.187.250.163:1521/IBANSYS
spring.datasource.username=trsf
spring.datasource.password=trsf
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

mstr.funds.client=mock
mstr.funds.blocking.client=mock



downstream.ms-ref.mode=DUMMY
downstream.ms-ref.mode.real-base-url=http://ms-ref:8080
downstream.ms-ref.mode.dummy-base-url=http://localhost:8091

