package com.smi.mstr.transfer.domain.enums;

public enum OperationEventType {
    OPERATION_CREATED,
    DRAFT_SAVED,
    INBOUND_REQUEST_LINKED,
    INBOUND_REQUEST_COMPLETED,
    ORDER_UPDATED,
    ORDER_VIEWED,

    PAYMENT_MODALITIES_UPDATED,
    PAYMENT_RESOURCE_AVAILABILITY_CHECKED,
    PAYMENT_SECURITY_APPLIED,
    PAYMENT_SECURITY_STATUS_VIEWED
}