package com.smi.mstr.transfer.domain.enums;

public enum OperationEventType {

    OPERATION_CREATED,
    DRAFT_SAVED,
    ORDER_UPDATED,
    DEBTOR_UPDATED,
    CREDITOR_UPDATED,
    QUALIFICATION_UPDATED,

    TOILETTE_CONTROL_RUN,
    VALIDATION_ERROR_DETECTED,
    VALIDATION_PASSED,
    VALIDATION_FAILED,

    PAYMENT_MODALITIES_UPDATED,
    PAYMENT_AVAILABILITY_CHECKED,
    PAYMENT_RESOURCES_SECURED,
    PAYMENT_SECURITY_FAILED,
    PAYMENT_RESOURCES_RELEASED,

    SUPPORT_ADDED,
    SUPPORT_UPDATED,
    SUPPORT_VALIDATED,
    SUPPORT_REJECTED,
    SUPPORT_RESERVED,
    SUPPORT_RESERVATION_FAILED,
    SUPPORT_IMPUTED,
    SUPPORT_IMPUTATION_FAILED,

    INTERBANK_DEFAULT_CHAIN_FETCHED,
    INTERBANK_CHAIN_UPDATED,
    INTERBANK_INSTRUCTIONS_UPDATED,
    INTERBANK_COVER_DETERMINED,
    INTERBANK_CONTROL_RUN,
    INTERBANK_CONTROL_FAILED,

    WORKFLOW_SUBMITTED,
    WORKFLOW_TASK_ASSIGNED,
    WORKFLOW_DECISION_RECEIVED,
    WORKFLOW_APPROVED,
    WORKFLOW_REJECTED,
    WORKFLOW_RETURNED_FOR_CORRECTION,

    STATUS_CHANGED,
    OPERATION_VALIDATED,
    OPERATION_EXECUTED,
    OPERATION_CANCELLED,
    OPERATION_REJECTED,

    TECHNICAL_EXCEPTION,
    BUSINESS_EXCEPTION
}