package com.smi.mstr.transfer.domain.enums;

public enum OperationEventType {
    OPERATION_CREATED,
    DRAFT_SAVED,
    INBOUND_REQUEST_LINKED,
    INBOUND_REQUEST_COMPLETED,
    ORDER_UPDATED,
    ORDER_VIEWED,

    PAYMENT_MODALITIES_UPDATED,
    PAYMENT_RESOURCE_AVAILABILITY_CHECKED,
    PAYMENT_SECURITY_APPLIED,
    PAYMENT_SECURITY_STATUS_VIEWED,
    PAYMENT_VALIDATION_RESULT_VIEWED,
    INTERBANK_ENRICHMENT_REQUESTED,
    INTERBANK_ENRICHMENT_COMPLETED,
    INTERBANK_ENRICHMENT_FAILED,
    INTERBANK_AGENT_UPDATED,
    NOSTRO_SELECTED,
    INTERBANK_MANUAL_REVIEW_REQUIRED,
    INTERBANK_DEFAULT_CHAIN_FETCHED
}