package com.smi.mstr.transfer.application.mock;

import com.smi.mstr.transfer.application.FicheInformationService;
import com.smi.mstr.transfer.application.context.WorkflowCommandContext;
import com.smi.mstr.transfer.domain.entity.MvtTrOperation;
import com.smi.mstr.transfer.domain.entity.TrSupportReglementaire;
import com.smi.mstr.transfer.domain.enums.StatutImputationSupport;
import com.smi.mstr.transfer.domain.enums.StatutReservationSupport;
import com.smi.mstr.transfer.domain.enums.StatutSupportReglementaire;
import com.smi.mstr.transfer.domain.enums.StatutValidationSupport;
import com.smi.mstr.transfer.domain.enums.TypeSupportReglementaire;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Year;
import java.util.Comparator;

@Service
@ConditionalOnProperty(
        name = "downstream.fiche-information.mode",
        havingValue = "MOCK",
        matchIfMissing = true
)
public class MockFicheInformationService implements FicheInformationService {

    private static final String SOURCE_SYSTEM = "MS-TR-FICHE-MOCK";
    private static final String AUTORITE_EMETTRICE = "MS-TR";

    @Override
    public TrSupportReglementaire generateFor(
            MvtTrOperation operation,
            WorkflowCommandContext context
    ) {
        validateOperation(operation);

        TrSupportReglementaire existingFiche = findExistingFicheInformation(operation);

        if (existingFiche != null) {
            updateExistingFiche(existingFiche, operation, context);
            return existingFiche;
        }

        TrSupportReglementaire fiche = buildNewFicheInformation(operation, context);
        operation.addSupportReglementaire(fiche);

        return fiche;
    }

    private TrSupportReglementaire buildNewFicheInformation(
            MvtTrOperation operation,
            WorkflowCommandContext context
    ) {
        LocalDate today = LocalDate.now();

        return TrSupportReglementaire.builder()
                .sequenceNo(nextSequenceNo(operation))
                .typeSupport(TypeSupportReglementaire.FICHE_INFORMATION)
                .codeSupportBct(null)

                .numSupport(generateFicheNumber(operation))
                .dateSupport(today)
                .autoriteEmettrice(AUTORITE_EMETTRICE)

                .numIdentification(generateIdentificationNumber(operation))
                .dateIdentification(today)

                .codeRd(null)
                .modeReglement(null)
                .numMessageSwift(operation.getTransactionId())
                .codeBanque(operation.getCodeAgence())

                .deviseSupport(operation.getCodeDevise())
                .montantAutorise(operation.getMntDevise())
                .montantUtiliseAvant(null)
                .montantReserve(operation.getMntDevise())
                .montantUtiliseCourant(null)
                .reliquatAvant(operation.getMntDevise())
                .reliquatApres(operation.getMntDevise())
                .montantTnd(operation.getContreValeurTnd())
                .coursConversion(operation.getCoursConversion())

                .statutSupport(StatutSupportReglementaire.ACTIVE)
                .statutValidation(StatutValidationSupport.VALIDATED)
                .statutReservation(StatutReservationSupport.NOT_REQUIRED)
                .statutImputation(StatutImputationSupport.PENDING)

                .messageValidation("Mock fiche d'information generated by MS-TR pending real FI service integration.")
                .sourceSystem(SOURCE_SYSTEM)
                .sourceReference(resolveSourceReference(context))
                .snapshotSupportJson(buildSnapshotJson(operation, context))

                .createdAt(LocalDateTime.now())
                .build();
    }

    private void updateExistingFiche(
            TrSupportReglementaire fiche,
            MvtTrOperation operation,
            WorkflowCommandContext context
    ) {
        fiche.setDateSupport(LocalDate.now());
        fiche.setDateIdentification(LocalDate.now());

        fiche.setNumMessageSwift(operation.getTransactionId());
        fiche.setCodeBanque(operation.getCodeAgence());

        fiche.setDeviseSupport(operation.getCodeDevise());
        fiche.setMontantAutorise(operation.getMntDevise());
        fiche.setMontantReserve(operation.getMntDevise());
        fiche.setReliquatAvant(operation.getMntDevise());
        fiche.setReliquatApres(operation.getMntDevise());
        fiche.setMontantTnd(operation.getContreValeurTnd());
        fiche.setCoursConversion(operation.getCoursConversion());

        fiche.setStatutSupport(StatutSupportReglementaire.ACTIVE);
        fiche.setStatutValidation(StatutValidationSupport.VALIDATED);
        fiche.setStatutReservation(StatutReservationSupport.NOT_REQUIRED);

        fiche.setMessageValidation("Mock fiche d'information refreshed by MS-TR.");
        fiche.setSourceSystem(SOURCE_SYSTEM);
        fiche.setSourceReference(resolveSourceReference(context));
        fiche.setSnapshotSupportJson(buildSnapshotJson(operation, context));
    }

    private TrSupportReglementaire findExistingFicheInformation(
            MvtTrOperation operation
    ) {
        if (operation.getSupportsReglementaires() == null) {
            return null;
        }

        return operation.getSupportsReglementaires()
                .stream()
                .filter(support -> support.getTypeSupport() == TypeSupportReglementaire.FICHE_INFORMATION)
                .findFirst()
                .orElse(null);
    }

    private Integer nextSequenceNo(MvtTrOperation operation) {
        if (operation.getSupportsReglementaires() == null
                || operation.getSupportsReglementaires().isEmpty()) {
            return 1;
        }

        return operation.getSupportsReglementaires()
                .stream()
                .map(TrSupportReglementaire::getSequenceNo)
                .filter(sequenceNo -> sequenceNo != null)
                .max(Comparator.naturalOrder())
                .orElse(0) + 1;
    }

    private String generateFicheNumber(MvtTrOperation operation) {
        String year = String.valueOf(Year.now().getValue());
        String sequence = String.format("%010d", operation.getRefOperation());

        return "FI-" + year + "-" + sequence;
    }

    private String generateIdentificationNumber(MvtTrOperation operation) {
        String sequence = String.format("%010d", operation.getRefOperation());

        return "ID-FI-" + sequence;
    }

    private String resolveSourceReference(WorkflowCommandContext context) {
        if (context == null) {
            return null;
        }

        if (notBlank(context.workflowInstanceId())) {
            return context.workflowInstanceId();
        }

        return context.correlationId();
    }

    private String buildSnapshotJson(
            MvtTrOperation operation,
            WorkflowCommandContext context
    ) {
        return """
                {
                  "mock": true,
                  "sourceSystem": "%s",
                  "operationRef": "%s",
                  "refOperation": %s,
                  "transferType": "%s",
                  "amount": %s,
                  "currency": "%s",
                  "counterValueTnd": %s,
                  "workflowInstanceId": "%s",
                  "workflowTaskId": "%s",
                  "generatedAt": "%s"
                }
                """.formatted(
                SOURCE_SYSTEM,
                nullToEmpty(operation.getRefOrdre()),
                operation.getRefOperation(),
                operation.getTypeTransfert(),
                operation.getMntDevise(),
                nullToEmpty(operation.getCodeDevise()),
                operation.getContreValeurTnd(),
                context == null ? "" : nullToEmpty(context.workflowInstanceId()),
                context == null ? "" : nullToEmpty(context.workflowTaskId()),
                LocalDateTime.now()
        );
    }

    private void validateOperation(MvtTrOperation operation) {
        if (operation == null) {
            throw new IllegalArgumentException("Operation is required to generate fiche d'information.");
        }

        if (operation.getRefOperation() == null) {
            throw new IllegalStateException("Operation must be persisted before generating fiche d'information.");
        }

        if (operation.getTypeTransfert() == null) {
            throw new IllegalStateException("Transfer type is required to generate fiche d'information.");
        }

        if (operation.getMntDevise() == null) {
            throw new IllegalStateException("Transfer amount is required to generate fiche d'information.");
        }

        if (operation.getCodeDevise() == null || operation.getCodeDevise().isBlank()) {
            throw new IllegalStateException("Transfer currency is required to generate fiche d'information.");
        }
    }

    private boolean notBlank(String value) {
        return value != null && !value.isBlank();
    }

    private String nullToEmpty(Object value) {
        return value == null ? "" : String.valueOf(value);
    }
}